In [1]:
import numpy as np



In [2]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [3]:
a.dtype

dtype('int64')

In [4]:
a[2] = 12345
a

array([   10,    20, 12345,    40,    50])

In [5]:
a[2] = 12.345
a

array([10, 20, 12, 40, 50])

In [6]:
a[2] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [7]:
import pandas as pd

In [8]:
from pandas import Series, DataFrame

In [9]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
s.dtype

dtype('int64')

In [11]:
s.values

array([10, 20, 30, 40, 50])

In [12]:
type(s.values)

numpy.ndarray

In [13]:
s.loc[2] = 12345
s

0       10
1       20
2    12345
3       40
4       50
dtype: int64

In [14]:
s.loc[2] = 12.345
s

0    10.000
1    20.000
2    12.345
3    40.000
4    50.000
dtype: float64

In [15]:
s.loc[2] = 'hello'

In [16]:
s

0     10.0
1     20.0
2    hello
3     40.0
4     50.0
dtype: object

In [17]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [19]:
s.loc[2] = np.nan

In [20]:
s

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64

In [21]:
s = Series('abcd ef ghi'.split())
s

0    abcd
1      ef
2     ghi
dtype: object

In [22]:
s.loc[1] = np.nan

In [23]:
s

0    abcd
1     NaN
2     ghi
dtype: object

In [24]:
type(np.nan)

float

In [27]:
s = Series([10, 20, 30, 40, 50], dtype=pd.Int64Dtype())
s

0    10
1    20
2    30
3    40
4    50
dtype: Int64

In [28]:
s.sum()

150

In [29]:
s.dtype

Int64Dtype()

In [30]:
s.loc[2] = np.nan

In [31]:
s

0      10
1      20
2    <NA>
3      40
4      50
dtype: Int64

In [33]:
pd.NA

<NA>

In [34]:
s.loc[3] = 12.345

TypeError: Invalid value '12.345' for dtype Int64

In [35]:
df = DataFrame({'a':[10, 20, 30],
                'b':[12.34, 56.78, 90.12],
                'c':'hello out there'.split()})

In [36]:
df

a      b      c
0  10  12.34  hello
1  20  56.78    out
2  30  90.12  there

In [37]:
df.dtypes

a      int64
b    float64
c     object
dtype: object

In [39]:
df = df.convert_dtypes()
df

a      b      c
0  10  12.34  hello
1  20  56.78    out
2  30  90.12  there

In [40]:
df.dtypes

a             Int64
b           Float64
c    string[python]
dtype: object

In [41]:
df.loc[2, 'c'] = pd.NA

In [42]:
df

a      b      c
0  10  12.34  hello
1  20  56.78    out
2  30  90.12   <NA>

In [43]:
df.dtypes

a             Int64
b           Float64
c    string[python]
dtype: object

In [44]:
df.dropna()

a      b      c
0  10  12.34  hello
1  20  56.78    out

In [45]:
df.fillna(10)

TypeError: Cannot set non-string value '10' into a StringArray.

In [46]:
df.fillna('10')

a      b      c
0  10  12.34  hello
1  20  56.78    out
2  30  90.12     10